[package]
name = "image_effects"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1.1.4"
image = "0.23.14"
num-complex = "0.4.0"


[build-dependencies]
fl2rust = "0.4"